FROM python:3.12-slim

# Install necessary packages
RUN apt-get update && apt-get install -y cron

# Set working directory
WORKDIR /be

# Add PYTHONPATH to include the project root
ENV PYTHONPATH="/be:${PYTHONPATH}"

# Copy Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code
COPY . .



# Copy the entrypoint script
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Expose port
EXPOSE 8041

# Set the entrypoint
ENTRYPOINT ["/entrypoint.sh"]
