version: '3'

services:
  # Service to run the backend API using Gunicorn
  inc-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: nebularamailo77/django_starter_template:dev
    container_name: inc-be-dev
    ports:
      - "8041:8041"
    env_file:
      - .env
    networks:
      - inc
    environment:
      - RUN_MIGRATIONS=true
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8041

networks:
  inc:
    driver: bridge
