version: 2.1

jobs:
  build_and_push_on_main:
    docker:
      - image: kopilb/aws-docker:v0.1.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image and Push to DockerHub
          command: |
            echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
            echo "$ENV_DEV" | base64 -d >> /root/project/.env
            docker compose -f docker-compose.dev.yml build
            docker compose -f docker-compose.dev.yml push
            docker logout

  deploy_to_server_on_main:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Deploy Files and Start Services
          command: |
            sshpass -p "$SERVER_PASSWORD" scp ./docker-compose.dev.yml $SERVER_USER@$SERVER_HOST_IP:/home/$SERVER_USER/testing/docker-compose.dev.yml
            sudo apt update && sudo apt install sshpass -y
            echo "$ENV_DEV" | base64 -d >> ./.env
            scp ./.env $SERVER_USER@$SERVER_HOST_IP:/home/$SERVER_USER/testing/.env
            echo "$SERVER_PASSWORD" | sshpass ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST_IP "echo 'SSH connection successful'"
            sshpass -p "$SERVER_PASSWORD" scp -o StrictHostKeyChecking=no ./docker-compose.dev.yml $SERVER_USER@$SERVER_HOST_IP:/home/$SERVER_USER/testing/docker-compose.dev.yml
            
            # Confirm the file was copied
            sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST_IP "ls -l /home/$SERVER_USER/testing"
            
            # Pull and start the Docker containers
            sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST_IP "
              cd /home/$SERVER_USER/testing
              docker compose -f ./docker-compose.dev.yml pull && 
              docker compose -f ./docker-compose.dev.yml up --no-build --force-recreate -d
            "

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build_and_push_on_main:
          filters:
            branches:
              only:
                - main
      - deploy_to_server_on_main:
          requires:
            - build_and_push_on_main
          filters:
            branches:
              only:
                - main
