version: 2.1

jobs:
  build_and_push_on_main:
    docker:
      - image: kopilb/aws-docker:v0.1.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image and Push to DockerHub
          command: |
            echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
            echo "$ENV_DEV" | base64 -d >> /root/project/.env
            docker compose -f docker-compose.dev.yml build
            docker compose -f docker-compose.dev.yml push
            docker logout

  deploy_to_server_on_main:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Deploy Files and Start Services
          command: | 
            sudo apt install sshpass -y
            sshpass -p $SERVER_PASSWORD scp ./docker-compose.dev.yml $SERVER_USER@$SERVER_HOST_IP:/home/$SERVER_USER/testing/docker-compose.dev.yml          
            echo "$ENV_DEV" | base64 -d > ./.env
            sshpass -p $SERVER_PASSWORD scp ./.env $SERVER_USER@$SERVER_HOST_IP:/home/$SERVER_USER/testing/.env

            sshpass -p $SERVER_PASSWORD ssh $SERVER_USER@$SERVER_HOST_IP "echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
            cd /home/deployer/testing
            docker compose -f ./docker-compose.dev.yml pull
            docker compose -f ./docker-compose.dev.yml up --no-build --force-recreate -d"
            docker logout




workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build_and_push_on_main:
          filters:
            branches:
              only:
                - main
      - deploy_to_server_on_main:
          requires:
            - build_and_push_on_main
          filters:
            branches:
              only:
                - main
